import assert from 'node:assert/strict';
import fs from 'node:fs';
import { expectedCustomDieFaceCount, getCustomDieQuickRollMax, isCustomDieFullyNumeric, isNumericCustomDie, layoutCustomDieFaceText, normalizeCustomDieResultMode, toCustomDieRollSnapshot, validateCustomDieDefinition } from '../src/app/components/session/dice/diceCustomDie.ts';
import { groupCustomDieResults } from '../src/app/components/session/dice/customDieResultGrouping.ts';
import { addCustomQuickDie, addStandardQuickDie, buildQuickRollItems, clearQuickRoll, decrementQuickDie, type QuickRollEntry } from '../src/app/components/session/dice/diceQuickRollState.ts';
import type { SavedCustomDie } from '../src/app/components/session/dice/diceTypes.ts';
function read(path:string){return fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8')}
function symbolicDie(sides:4|6|8|10|12|20):SavedCustomDie{return{id:`custom-${sides}`,campaignId:'c',ownerProfileId:'u',name:'Ferite',sides,faces:Array.from({length:sides},(_,i)=>({index:i+1,role:'single' as const,visual:{kind:'icon' as const,iconName:['Skull','Shield','Sword','Heart'][i%4]},label:['Skull','Shield','Sword','Heart'][i%4],numericValue:null})),bodyColor:'#20242f',symbolColor:'#ffffff',skinId:'none',effectsEnabled:false,iconName:null,folderId:null,sortOrder:0,createdAt:'',updatedAt:''}}
assert.deepEqual([4,6,8,10,12,20,100].map((s)=>expectedCustomDieFaceCount(s as any)),[4,6,8,10,12,20,20]);
const d6=symbolicDie(6);assert.equal(validateCustomDieDefinition(d6).valid,true);assert.equal(isCustomDieFullyNumeric(d6),false);assert.equal(validateCustomDieDefinition({...d6,faces:d6.faces.slice(0,5)}).valid,false);
const numericD30={...d6,id:'numeric-d30',name:'d30',sides:30,definitionMode:'numeric' as const,resultDisplayMode:'single' as const,faces:[]};assert.equal(validateCustomDieDefinition(numericD30).valid,true);assert.equal(isNumericCustomDie(numericD30),true);assert.equal(isCustomDieFullyNumeric(numericD30),true);assert.equal(getCustomDieQuickRollMax(numericD30),1000);assert.equal(validateCustomDieDefinition({...numericD30,sides:20}).valid,true);assert.equal(validateCustomDieDefinition({...numericD30,sides:2}).valid,true);assert.equal(validateCustomDieDefinition({...numericD30,faces:d6.faces}).valid,false);assert.equal(validateCustomDieDefinition({...numericD30,resultDisplayMode:'grouped'}).valid,false);
assert.equal(validateCustomDieDefinition({...d6,faces:d6.faces.map((face,index)=>index===0?{...face,resultGroup:0}:face)}).valid,false);
const singleText=layoutCustomDieFaceText('+1');assert.deepEqual(singleText.lines,['+1']);assert.deepEqual(singleText.lineYs,[50]);const doubleText=layoutCustomDieFaceText('Elfo Oscuro');assert.deepEqual(doubleText.lines,['Elfo','Oscuro']);assert.equal(doubleText.lines.length,2);assert.ok(doubleText.lineYs[0]<50&&doubleText.lineYs[1]>50);
const snapshot=toCustomDieRollSnapshot({...d6,skinId:'arcane',effectsEnabled:true});assert.equal(snapshot.skinId,'arcane');assert.equal(snapshot.effectsEnabled,true);const legacySnapshot=toCustomDieRollSnapshot({...d6,skinId:undefined,effectsEnabled:undefined});assert.equal(legacySnapshot.skinId,'none');assert.equal(legacySnapshot.effectsEnabled,false);
assert.equal(normalizeCustomDieResultMode(undefined),'single');assert.equal(toCustomDieRollSnapshot({...d6,resultDisplayMode:'grouped'}).resultDisplayMode,'grouped');
const groupedSymbols=groupCustomDieResults({itemId:'symbols',sides:6,requestedQuantity:3,rolls:[
  {id:'r1',groupItemId:'symbols',sides:6,face:5,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'c1',customFace:{...d6.faces[4],resultGroup:1},physicalRole:'single',logicalRollIndex:0},
  {id:'r2',groupItemId:'symbols',sides:6,face:2,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'c2',customFace:{...d6.faces[1],resultGroup:2},physicalRole:'single',logicalRollIndex:1},
  {id:'r3',groupItemId:'symbols',sides:6,face:1,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'c3',customFace:{...d6.faces[0],visual:{kind:'icon',iconName:'SkullRound'},resultGroup:1},physicalRole:'single',logicalRollIndex:2},
],activeRollIds:['r1','r2','r3'],contribution:null});assert.deepEqual(groupedSymbols.map((entry)=>[entry.faces[0]?.label,entry.count]),[['Skull',2],['Shield',1]]);
const unassignedDuplicateSymbols=groupCustomDieResults({itemId:'unassigned',sides:6,requestedQuantity:2,rolls:[{id:'u1',groupItemId:'unassigned',sides:6,face:1,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'u1',customFace:d6.faces[0],physicalRole:'single',logicalRollIndex:0},{id:'u2',groupItemId:'unassigned',sides:6,face:5,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'u2',customFace:d6.faces[4],physicalRole:'single',logicalRollIndex:1}],activeRollIds:['u1','u2'],contribution:null});assert.equal(unassignedDuplicateSymbols.length,2,'unassigned faces must remain distinct even when their visuals match');
const d100Faces=[{index:2,role:'tens' as const,visual:{kind:'text' as const,text:'20'},label:'20',numericValue:20},{index:4,role:'units' as const,visual:{kind:'text' as const,text:'4'},label:'4',numericValue:4}];const groupedD100=groupCustomDieResults({itemId:'d100',sides:100,requestedQuantity:2,rolls:[0,1].flatMap((logicalRollIndex)=>d100Faces.map((customFace,index)=>({id:`d100-${logicalRollIndex}-${index}`,groupItemId:'d100',sides:index===0?100:10,face:customFace.index,contribution:index===0?24:0,active:true,source:'base' as const,explosionDepth:0,chainId:`c${logicalRollIndex}`,customFace,physicalRole:customFace.role,logicalRollIndex}))),activeRollIds:[],contribution:48});assert.equal(groupedD100.length,1);assert.equal(groupedD100[0]?.count,2);assert.equal(groupedD100[0]?.faces.length,2);
let quick:QuickRollEntry[]=[];for(let i=0;i<5;i++)quick=addStandardQuickDie(quick,6);quick=addStandardQuickDie(quick,20);quick=addCustomQuickDie(quick,d6.id);quick=addCustomQuickDie(quick,d6.id);assert.deepEqual(quick.map((entry)=>entry.quantity),[5,1,2]);quick=decrementQuickDie(quick,{kind:'custom-die',customDieId:d6.id,quantity:2});assert.equal(quick.find((entry)=>entry.kind==='custom-die')?.quantity,1);assert.deepEqual(clearQuickRoll(),[]);
let customMultiples:QuickRollEntry[]=[];for(let i=0;i<3;i++){customMultiples=addCustomQuickDie(customMultiples,d6.id,3);assert.equal(customMultiples[0]?.quantity,(i+1)*3)}
const resolved=buildQuickRollItems([{kind:'custom-die',customDieId:d6.id,quantity:3}],[d6]);assert.equal(resolved[0]?.kind,'custom-die');if(resolved[0]?.kind==='custom-die'){assert.equal(resolved[0].customDie.skinId,'none');assert.equal(resolved[0].quantity,3)}
const floating=read('src/app/components/session/dice/DiceQuickRollFloating.tsx');const configurator=read('src/app/components/session/dice/CustomDieConfigurator.tsx');const panel=read('src/app/components/session/dice/SessionDicePanel.tsx');const service=read('src/services/supabase/diceCustomDiceService.ts');const card=read('src/app/components/session/dice/DiceRollHistoryCard.tsx');const quantityMigration=read('supabase/migrations/20260916120000_dice_custom_dice_quick_roll_quantity.sql');const resultModeMigration=read('supabase/migrations/20260918120000_dice_custom_dice_result_display_mode.sql');const faceGroupMigration=read('supabase/migrations/20260918160000_dice_custom_die_face_groups.sql');const dxxMigration=read('supabase/migrations/20260918200000_dice_custom_die_dxx.sql');const numericModeMigration=read('supabase/migrations/20260918210000_dice_custom_die_numeric_mode.sql');
for(const hook of ['data-dice-quick-roll-floating','data-dice-quick-palette','data-dice-custom-toolbar','data-dice-custom-selector-popover','data-dice-history-unread'])assert.ok(floating.includes(hook),`missing ${hook}`);
assert.ok(floating.indexOf('SIDES.map')<floating.indexOf('data-dice-custom-toolbar'),'Custom selector must follow standard dice');assert.ok(/formulaName:\s*'Tiro rapido'/.test(floating));assert.ok(/setEntries\(clearQuickRoll\(\)\)/.test(floating),'successful quick roll must reset the pool');assert.ok(!floating.includes('data-dice-custom-quick-stepper')&&!floating.includes('data-dice-custom-quick-increment')&&!floating.includes('data-dice-custom-quick-decrement'),'custom quick dice must not use +/- steppers');assert.ok(!floating.includes('decrementQuickDie'),'custom quick dice must not offer a decrement path');assert.ok(/customQty\s*=\s*\(customDieId/.test(floating),'custom quick dice must track per-die tap counts');assert.ok(floating.includes('customQty(die.id)')&&floating.includes('-right-1 -top-1'),'each custom die tap must show a count badge like standard dice');assert.ok(floating.includes('-right-1 -top-1 z-20'),'custom count badge must paint above the custom die artwork');assert.ok(floating.includes('data-dice-custom-selector-grid')&&floating.includes('gap-2')&&floating.includes('overflow-x-auto p-1'),'custom selector grid must leave breathing room so badges are not clipped at the edges');assert.ok(floating.includes('!animate-none'),'Custom selector tooltip must remain immediate');assert.ok(floating.includes('<StyledStandardDieIcon')&&floating.includes('appearance={getStandardAppearance(side)}'),'standard quick dice must display current saved appearance');assert.ok(floating.indexOf('data-dice-custom-toolbar')<floating.indexOf('data-dice-appearance-toolbar'),'Personalizza must follow Custom selector');assert.ok(floating.includes("die.sides === 100 ? 'w-[4.25rem]' : 'w-9'")&&floating.includes("size={die.sides === 100 ? 'card' : 'compact'}"),'quick-roll d100 pair must render at card size instead of microscopic');
assert.ok(configurator.includes('data-custom-die-skin-controls')&&configurator.includes('data-custom-die-effects'));assert.ok(configurator.includes("initial?.skinId ?? 'none'")&&configurator.includes('initial?.effectsEnabled ?? false'));assert.ok(/onSave\(\{\s*id,[\s\S]{0,180}skinId,\s*effectsEnabled/.test(configurator));assert.ok(/skinId:\s*DiceSkinId/.test(panel)&&/effectsEnabled:\s*boolean/.test(panel));assert.ok(/skinId:\s*d\.skinId/.test(panel)&&/effectsEnabled:\s*d\.effectsEnabled/.test(panel));
assert.ok(configurator.includes('data-custom-die-quick-roll-quantity')&&configurator.includes('initial?.quickRollQuantity ?? 1'),'configurator must edit the saved quick-roll quantity');assert.ok(configurator.indexOf('data-custom-die-quick-roll-quantity')>configurator.indexOf('Geometria'),'quantity selector must follow geometry');assert.ok(configurator.includes('max={getCustomDieQuickRollMax({ sides, definitionMode })}'),'percentile d100 quantity must respect the physical dice cap');assert.ok(configurator.includes('integer fullWidth ariaLabel="Quantità tiro rapido"'),'configurator quantity must center in the full-width stepper');assert.ok(floating.includes('addCustomQuickDie(value, die.id, die.quickRollQuantity)'),'quick selector clicks must add the saved quantity');assert.ok(panel.includes('quickRollQuantity:d.quickRollQuantity'),'create and edit must save the quantity');for(const token of ['quick_roll_quantity: input.quickRollQuantity ?? 1','payload.quick_roll_quantity = patch.quickRollQuantity','quickRollQuantity: die.quickRollQuantity ?? 1'])assert.ok(service.includes(token),`missing persisted quantity flow: ${token}`);assert.ok(quantityMigration.includes('quick_roll_quantity integer not null default 1')&&quantityMigration.includes('when sides = 100 then 500 else 1000'),'migration must preserve legacy defaults and enforce the roll cap');
assert.ok(configurator.includes('data-custom-die-result-mode')&&configurator.includes("initial?.resultDisplayMode ?? 'single'"),'configurator must expose the persisted result mode');assert.ok(configurator.includes('items-start')&&configurator.includes('content-start auto-rows-max'),'configurator columns and face cards must not stretch vertically');assert.ok(panel.includes('resultDisplayMode:d.resultDisplayMode'),'create and edit must save the result mode');for(const token of ['result_display_mode: normalizeCustomDieResultMode(input.resultDisplayMode)','payload.result_display_mode = normalizeCustomDieResultMode(patch.resultDisplayMode)','resultDisplayMode: normalizeCustomDieResultMode(die.resultDisplayMode)'])assert.ok(service.includes(token),`missing persisted result mode flow: ${token}`);assert.ok(resultModeMigration.includes("default 'single'")&&resultModeMigration.includes("in ('single', 'grouped')"),'migration must preserve legacy behavior and constrain result modes');assert.ok(card.includes('data-custom-die-grouped-result')&&card.includes('data-custom-die-group-count')&&card.includes('data-custom-die-grouped-total'),'history must render grouped Custom outcomes, counts, and final total');
assert.ok(/data-custom-die-grouped-result[^>]*gap-0\.5/.test(card)&&/data-custom-die-group-count[^>]*text-\[24px\]/.test(card)&&!/data-custom-die-group-count[^>]*ml-auto/.test(card),'group counts must sit close to the die at the same visual size');
assert.ok(configurator.includes('data-custom-die-face-group')&&configurator.includes("resultDisplayMode === 'grouped'"),'group mode must expose a group number on every face');assert.ok(configurator.indexOf('data-custom-die-appearance-controls')>configurator.indexOf('data-custom-die-face-group'),'appearance controls must be distributed below the face grid');assert.ok(faceGroupMigration.includes("v_face ? 'resultGroup'")&&faceGroupMigration.includes('v_group<>trunc(v_group)'),'database must reject invalid face groups');
assert.ok(configurator.includes('data-custom-die-dxx')&&configurator.indexOf('data-custom-die-dxx')>configurator.indexOf('d100'),'dXX must be offered after the legacy percentile d100');assert.ok(configurator.includes('min={MIN_CUSTOM_DIE_SIDES}')&&configurator.includes('max={MAX_CUSTOM_DIE_SIDES}'),'dXX must constrain custom sides to 2..999');assert.ok(configurator.includes('Il dXX non viene simulato in 3D'),'numeric dXX must explain its intentional 3D omission');assert.ok(configurator.includes("changeSides(MIN_CUSTOM_DIE_SIDES, 'numeric')"),'dXX entry must default to 2 faces');for(const token of ['definition_mode text not null',"sides between 2 and 999","definition_mode='numeric'","jsonb_array_length(new.faces)<>0"])assert.ok(dxxMigration.includes(token),`dXX migration missing ${token}`);for(const token of ['definition_mode: normalizeCustomDieDefinitionMode','payload.definition_mode = normalizeCustomDieDefinitionMode','definitionMode: normalizeCustomDieDefinitionMode'])assert.ok(service.includes(token),`missing persisted dXX mode flow: ${token}`);assert.ok(card.includes('forceGeneric={Boolean(group.customDieSnapshot && isNumericCustomDie(group.customDieSnapshot))}'),'numeric Custom dice, including d100, must use a generic dN history result');
assert.ok(configurator.includes('data-custom-die-definition-mode')&&configurator.includes('Numeri Standard')&&configurator.includes('Facce Custom'),'dXX must expose both definition modes');assert.ok(configurator.includes('<DiceNumericStepper value={sides}')&&!configurator.includes('customSidesDraft'),'dXX sides must use the shared +/- stepper');assert.ok(configurator.includes("option.value === 'faces' && sides > 20"),'custom faces must be disabled above d20');assert.ok(numericModeMigration.includes("if new.definition_mode='numeric' then")&&!numericModeMigration.includes('new.sides<=20'),'database must accept numeric dXX from d2 through d999');
console.log('Custom dice quick-roll verification passed.');
