import assert from 'node:assert/strict';import fs from 'node:fs';
import { boostDice3DSpin,DICE_3D_SPIN_MULTIPLIER,DICE_3D_THROW_STRENGTH } from '../src/app/components/session/dice/dice3dMotion.ts';
import { projectRollTo3D } from '../src/app/components/session/dice/dice3dProjection.ts';
import type { CustomDieRollSnapshot,RollDiceGroup,RollResult } from '../src/app/components/session/dice/diceTypes.ts';
function group(itemId:string,sides:number,faces:number[]):RollDiceGroup{const rolls=faces.map((face,index)=>({id:`${itemId}-${index}`,groupItemId:itemId,sides,face,contribution:face,active:true,source:'base' as const,explosionDepth:0,chainId:`${itemId}-${index}`}));return{itemId,sides,requestedQuantity:faces.length,rolls,activeRollIds:rolls.map(r=>r.id),contribution:faces.reduce((a,b)=>a+b,0)}}
function result(groups:RollDiceGroup[]):RollResult{return{id:'r',campaignId:'c',rollerId:'u',rollerName:'T',formulaName:'3D',formulaText:'test',visibility:'public',sourceItems:[],diceGroups:groups,arithmeticSteps:[],comparisons:[],total:0,createdAt:1}}
assert.deepEqual(projectRollTo3D(result([group('d20',20,[17,4])])),[{sides:20,values:[17,4],notation:'2d20@17,4'}]);
const standard=projectRollTo3D(result([group('d4',4,[3]),group('d6',6,[6]),group('d8',8,[7]),group('d10',10,[9]),group('d12',12,[11]),group('d20',20,[19]),group('d100',100,[73])]));
assert.deepEqual(standard.map(c=>c.notation),['1d4@3','1d6@6','1d8@7','1d10@9','1d12@11','1d20@19','1d100@70','1d10@3']);
const snap:CustomDieRollSnapshot={id:'custom',name:'Custom',sides:6,faces:Array.from({length:6},(_,i)=>({index:i+1,role:'single',visual:{kind:'icon',iconName:'Star'},numericValue:null})),bodyColor:'#111111',symbolColor:'#ffffff'};
const customGroup:RollDiceGroup={...group('custom',6,[2,5]),customDieId:'custom',customDieName:'Custom',customDieSnapshot:snap,rolls:group('custom',6,[2,5]).rolls.map((r,i)=>({...r,customDieId:'custom',customFace:snap.faces[i?4:1],physicalRole:'single',logicalRollIndex:i,contribution:null})),contribution:null};
const projected=projectRollTo3D(result([customGroup]));assert.deepEqual(projected.map(c=>c.values),[[2],[5]]);assert.ok(projected.every(c=>c.customMaterials?.[0]?.customDie.id==='custom'));
const d100Snap:CustomDieRollSnapshot={...snap,id:'p',sides:100,faces:[...Array.from({length:10},(_,i)=>({index:i+1,role:'tens' as const,visual:{kind:'icon' as const,iconName:'Star'},numericValue:null})),...Array.from({length:10},(_,i)=>({index:i+1,role:'units' as const,visual:{kind:'icon' as const,iconName:'Star'},numericValue:null}))]};
const pair:RollDiceGroup={itemId:'p',sides:100,requestedQuantity:1,rolls:[{id:'t',groupItemId:'p',sides:100,face:4,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'c',customDieId:'p',customFace:d100Snap.faces[3],physicalRole:'tens',logicalRollIndex:0},{id:'u',groupItemId:'p',sides:10,face:7,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'c',customDieId:'p',customFace:d100Snap.faces[16],physicalRole:'units',logicalRollIndex:0}],activeRollIds:['t','u'],contribution:null,customDieId:'p',customDieSnapshot:d100Snap};
assert.deepEqual(projectRollTo3D(result([pair])).map(c=>c.notation),['1d100@40','1d10@7']);
assert.equal(DICE_3D_THROW_STRENGTH,1.4);assert.equal(DICE_3D_SPIN_MULTIPLIER,1.2);const motion={vectors:[{angle:{x:5,y:-10,z:0}},{angle:{x:0,y:0,z:0}},{}]};assert.equal(boostDice3DSpin(motion),motion);assert.deepEqual(motion.vectors[0].angle,{x:6,y:-12,z:0});assert.deepEqual(motion.vectors[1].angle,{x:0,y:0,z:0});
const renderer=fs.readFileSync(new URL('../src/app/components/session/dice/dice3dRenderer.ts',import.meta.url),'utf8');const materials=fs.readFileSync(new URL('../src/app/components/session/dice/dice3dCustomMaterials.ts',import.meta.url),'utf8');
assert.ok(renderer.includes("await import('@3d-dice/dice-box-threejs')"));assert.equal((renderer.match(/this\.box\.roll\(/g)??[]).length,1);assert.ok(renderer.includes('installCustomDiceMaterialAdapter'));assert.ok(renderer.includes('installDice3DSpinAdapter(box)'));assert.ok(renderer.includes('strength: DICE_3D_THROW_STRENGTH'));assert.ok(renderer.includes('try {'));assert.ok(renderer.includes('finally'));
assert.ok(materials.includes('ICON_DATA'));assert.ok(materials.includes("physicalSides === 4"));assert.ok(materials.includes('buildSimultaneousMaterialQueue'));
console.log('Dice 3D verification passed.');
