import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(p)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const toolbar=read('src/app/components/session/dice/DiceToolbar.tsx');
const builder=read('src/app/components/session/dice/DiceFormulaBuilder.tsx');
const row=read('src/app/components/session/dice/DiceFormulaRow.tsx');
const panel=read('src/app/components/session/dice/SessionDicePanel.tsx');
const saved=read('src/app/components/session/dice/SavedDiceFormulaCard.tsx');
const history=read('src/app/components/session/dice/DiceRollHistoryDrawer.tsx');
const card=read('src/app/components/session/dice/DiceRollHistoryCard.tsx');
const quick=read('src/app/components/session/dice/DiceQuickRollFloating.tsx');
const custom=read('src/app/components/session/dice/CustomDieConfigurator.tsx');
const customizer=read('src/app/components/session/dice/DiceAppearanceCustomizer.tsx');
const customDie=read('src/app/components/session/dice/diceCustomDie.ts');
assert.match(toolbar,/QUICK_DICE_SIDES\s*=\s*\[4,\s*6,\s*8,\s*10,\s*12,\s*20,\s*100\]/);
assert.ok(toolbar.includes('DiceTypeIcon')); assert.ok(toolbar.includes('TooltipContent')); assert.ok(toolbar.includes('data-dice-custom-toolbar'));
for(const family of ['compare','dice','drop','exploding','keep','modifier']) assert.ok(builder.includes(`append('${family}')`));
for(const hook of ['data-dice-formula-row','data-dice-drop-position','data-dice-drop-indicator','data-dice-drag-ghost']) assert.ok(row.includes(hook));
for(const text of ['Sposta su','Sposta giù','INTERACTIVE_DRAG_SELECTOR','input, select, button','setDragImage','event.clientY','getBoundingClientRect()','<option value="equal">Uguale</option>','ariaLabel="Soglia Mantieni"','data-dice-custom-formula-select']) assert.ok(row.includes(text),`missing ${text}`);
for(const hook of ['data-dice-roll-builder','data-dice-save-formula','data-dice-clear-builder','data-dice-new-folder']) assert.ok(panel.includes(hook));
for(const hook of ['data-saved-dice-formula','data-dice-visibility-toggle','data-dice-formula-edit','data-dice-formula-duplicate','data-dice-formula-delete']) assert.ok(saved.includes(hook));
for(const hook of ['data-dice-history-drawer','data-dice-history-scroll','data-dice-history-scrollbar-track','data-dice-history-scrollbar-thumb','data-dice-3d-toggle','data-dice-history-clear']) assert.ok(history.includes(hook));
assert.ok(history.includes('Pulisci')); assert.ok(/scrollContainer\.scrollTop\s*=\s*scrollContainer\.scrollHeight/.test(history)); assert.ok(history.includes('max-h-[58vh]')); assert.ok(history.includes('min-w-[18rem]')); assert.ok(history.includes('max-w-[min(24rem,calc(100vw-8rem))]')); assert.ok(history.includes('<DiceQuickRollFloating />'));
assert.ok(card.includes('formatPrimaryRollResult(result)')); assert.ok(card.includes('data-dice-player-actions')); assert.ok(card.includes('data-dice-reroll')); assert.ok(/result\.visibility\s*===\s*'secret'/.test(card)); assert.ok(card.includes('Segreto')); assert.ok(card.includes('CustomDieFaceResult'));
assert.ok(card.includes("import { StyledStandardDieIcon } from './StyledStandardDieIcon';"), 'dice history must render standard result snapshots with the shared styled die icon');
assert.ok(card.includes('CHAT_DIE_SIDES = [4, 6, 8, 10, 12, 20, 100]'), 'dice history must recognize every standard Hollowgate die shape');
assert.ok(/<StandardDieResult[\s\S]{0,220}appearance=\{group\.appearance\}/.test(card), 'standard history results must use the appearance snapshot stored on the roll group');
assert.ok(!card.includes('<Dices className="h-2.5 w-2.5"/>d{die.sides}:'), 'standard numeric results must not use the generic two-dice icon plus dXX label');
for(const hook of ['data-dice-quick-roll-floating','data-dice-quick-toggle','data-dice-history-toggle','data-dice-history-unread','data-dice-quick-palette','data-dice-appearance-toolbar']) assert.ok(quick.includes(hook));
assert.ok(quick.indexOf('data-dice-custom-toolbar') < quick.indexOf('data-dice-appearance-toolbar'), 'Personalizza must immediately follow the Custom die control');
assert.ok(quick.includes('appearance={getStandardAppearance(side)}'), 'quick-roll standard dice must read the campaign/user appearance context');
assert.ok(quick.includes('isLoading: appearanceLoading') && /data-dice-appearance-toolbar[\s\S]{0,260}disabled=\{appearanceLoading\}/.test(quick), 'Personalizza must not open before stored styles finish loading');
for(const hook of ['data-dice-appearance-customizer','data-dice-appearance-side','data-dice-appearance-effects','data-dice-appearance-apply-all','data-dice-appearance-save','data-dice-appearance-cancel']) assert.ok(customizer.includes(hook),`customizer missing ${hook}`);
assert.ok(customizer.includes('DICE_SKINS.map'), 'standard customizer must expose the complete shared skin catalog');
assert.ok(customizer.includes('Applica a tutti') && customizer.includes('Colore dado') && customizer.includes('Colore numeri'));
for(const hook of ['data-custom-die-configurator','data-custom-die-face','data-custom-die-upload','data-custom-die-face-drag-source','data-custom-die-face-drop-target','data-custom-die-skin-controls','data-custom-die-effects']) assert.ok(custom.includes(hook));
assert.ok(/dataTransfer\.effectAllowed\s*=\s*'copy'/.test(custom),'custom face preview drag must advertise copy semantics');
assert.ok(/dataTransfer\.dropEffect\s*=\s*'copy'/.test(custom),'custom face drop target must use copy semantics');
assert.ok(/copyFaceVisual\(source,\s*pos\)/.test(custom),'dropping a custom face must copy its visual to the target');
assert.ok(/draggable=\{false\}[^>]*data-custom-die-image-preview/.test(custom),'image contents must not start their own native image drag');
assert.ok(/!isCustomDieImageAssetUsed\(next,\s*previous\.assetPath\)/.test(custom),'shared uploaded images must only be removed when no face still references them');
assert.ok(custom.includes("initial?.skinId ?? 'none'") && custom.includes('initial?.effectsEnabled ?? false'), 'legacy Custom dice must default to no skin/effects');
assert.ok(custom.includes('DICE_SKINS.map'), 'Custom configurator must use the same nine-skin catalog');
assert.ok(/onSave\(\{\s*id,[\s\S]{0,180}skinId,\s*effectsEnabled\s*\}\)/.test(custom), 'Custom save draft must include skin and effects');
assert.ok(customDie.includes('export function copyCustomDieFaceVisual'),'custom die visual copying must be isolated in a reusable helper');
assert.ok(/visual:\s*\{\s*\.\.\.source\.visual\s*\}/.test(customDie),'copying a visual must preserve target face metadata');
console.log('Dice UI verification passed.');
