import assert from 'node:assert/strict';
import fs from 'node:fs';
import { expectedCustomDieFaceCount, isCustomDieFullyNumeric, layoutCustomDieFaceText, toCustomDieRollSnapshot, validateCustomDieDefinition } from '../src/app/components/session/dice/diceCustomDie.ts';
import { addCustomQuickDie, addStandardQuickDie, buildQuickRollItems, clearQuickRoll, decrementQuickDie, type QuickRollEntry } from '../src/app/components/session/dice/diceQuickRollState.ts';
import type { SavedCustomDie } from '../src/app/components/session/dice/diceTypes.ts';
function read(path:string){return fs.readFileSync(new URL(`../${path}`,import.meta.url),'utf8')}
function symbolicDie(sides:4|6|8|10|12|20):SavedCustomDie{return{id:`custom-${sides}`,campaignId:'c',ownerProfileId:'u',name:'Ferite',sides,faces:Array.from({length:sides},(_,i)=>({index:i+1,role:'single' as const,visual:{kind:'icon' as const,iconName:['Skull','Shield','Sword','Heart'][i%4]},label:['Skull','Shield','Sword','Heart'][i%4],numericValue:null})),bodyColor:'#20242f',symbolColor:'#ffffff',skinId:'none',effectsEnabled:false,iconName:null,folderId:null,sortOrder:0,createdAt:'',updatedAt:''}}
assert.deepEqual([4,6,8,10,12,20,100].map((s)=>expectedCustomDieFaceCount(s as any)),[4,6,8,10,12,20,20]);
const d6=symbolicDie(6);assert.equal(validateCustomDieDefinition(d6).valid,true);assert.equal(isCustomDieFullyNumeric(d6),false);assert.equal(validateCustomDieDefinition({...d6,faces:d6.faces.slice(0,5)}).valid,false);
const singleText=layoutCustomDieFaceText('+1');assert.deepEqual(singleText.lines,['+1']);assert.deepEqual(singleText.lineYs,[50]);const doubleText=layoutCustomDieFaceText('Elfo Oscuro');assert.deepEqual(doubleText.lines,['Elfo','Oscuro']);assert.equal(doubleText.lines.length,2);assert.ok(doubleText.lineYs[0]<50&&doubleText.lineYs[1]>50);
const snapshot=toCustomDieRollSnapshot({...d6,skinId:'arcane',effectsEnabled:true});assert.equal(snapshot.skinId,'arcane');assert.equal(snapshot.effectsEnabled,true);const legacySnapshot=toCustomDieRollSnapshot({...d6,skinId:undefined,effectsEnabled:undefined});assert.equal(legacySnapshot.skinId,'none');assert.equal(legacySnapshot.effectsEnabled,false);
let quick:QuickRollEntry[]=[];for(let i=0;i<5;i++)quick=addStandardQuickDie(quick,6);quick=addStandardQuickDie(quick,20);quick=addCustomQuickDie(quick,d6.id);quick=addCustomQuickDie(quick,d6.id);assert.deepEqual(quick.map((entry)=>entry.quantity),[5,1,2]);quick=decrementQuickDie(quick,{kind:'custom-die',customDieId:d6.id,quantity:2});assert.equal(quick.find((entry)=>entry.kind==='custom-die')?.quantity,1);assert.deepEqual(clearQuickRoll(),[]);
const resolved=buildQuickRollItems([{kind:'custom-die',customDieId:d6.id,quantity:3}],[d6]);assert.equal(resolved[0]?.kind,'custom-die');if(resolved[0]?.kind==='custom-die'){assert.equal(resolved[0].customDie.skinId,'none');assert.equal(resolved[0].quantity,3)}
const floating=read('src/app/components/session/dice/DiceQuickRollFloating.tsx');const configurator=read('src/app/components/session/dice/CustomDieConfigurator.tsx');const panel=read('src/app/components/session/dice/SessionDicePanel.tsx');
for(const hook of ['data-dice-quick-roll-floating','data-dice-quick-palette','data-dice-custom-toolbar','data-dice-custom-selector-popover','data-dice-custom-quick-stepper','data-dice-history-unread'])assert.ok(floating.includes(hook),`missing ${hook}`);
assert.ok(floating.indexOf('SIDES.map')<floating.indexOf('data-dice-custom-toolbar'),'Custom selector must follow standard dice');assert.ok(/formulaName:\s*'Tiro rapido'/.test(floating));assert.ok(/setEntries\(clearQuickRoll\(\)\)/.test(floating),'successful quick roll must reset the pool');assert.ok(/customEntries\s*=\s*entries\.filter/.test(floating));assert.ok(/customEntries\.length\s*>\s*0/.test(floating));assert.ok(/customEntries\.map/.test(floating));assert.ok(floating.includes('!animate-none'),'Custom selector tooltip must remain immediate');assert.ok(floating.includes('<StyledStandardDieIcon')&&floating.includes('appearance={getStandardAppearance(side)}'),'standard quick dice must display current saved appearance');assert.ok(floating.indexOf('data-dice-custom-toolbar')<floating.indexOf('data-dice-appearance-toolbar'),'Personalizza must follow Custom selector');
assert.ok(configurator.includes('data-custom-die-skin-controls')&&configurator.includes('data-custom-die-effects'));assert.ok(configurator.includes("initial?.skinId ?? 'none'")&&configurator.includes('initial?.effectsEnabled ?? false'));assert.ok(/onSave\(\{\s*id,[\s\S]{0,180}skinId,\s*effectsEnabled/.test(configurator));assert.ok(/skinId:\s*DiceSkinId/.test(panel)&&/effectsEnabled:\s*boolean/.test(panel));assert.ok(/skinId:\s*d\.skinId/.test(panel)&&/effectsEnabled:\s*d\.effectsEnabled/.test(panel));
console.log('Custom dice quick-roll verification passed.');
