import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(p)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const toolbar=read('src/app/components/session/dice/DiceToolbar.tsx');
const builder=read('src/app/components/session/dice/DiceFormulaBuilder.tsx');
const row=read('src/app/components/session/dice/DiceFormulaRow.tsx');
const panel=read('src/app/components/session/dice/SessionDicePanel.tsx');
const saved=read('src/app/components/session/dice/SavedDiceFormulaCard.tsx');
const history=read('src/app/components/session/dice/DiceRollHistoryDrawer.tsx');
const card=read('src/app/components/session/dice/DiceRollHistoryCard.tsx');
const quick=read('src/app/components/session/dice/DiceQuickRollFloating.tsx');
const custom=read('src/app/components/session/dice/CustomDieConfigurator.tsx');
const customDie=read('src/app/components/session/dice/diceCustomDie.ts');
assert.match(toolbar,/QUICK_DICE_SIDES\s*=\s*\[4,\s*6,\s*8,\s*10,\s*12,\s*20,\s*100\]/);
assert.ok(toolbar.includes('DiceTypeIcon')); assert.ok(toolbar.includes('TooltipContent')); assert.ok(toolbar.includes('data-dice-custom-toolbar'));
for(const family of ['compare','dice','drop','exploding','keep','modifier']) assert.ok(builder.includes(`append('${family}')`));
for(const hook of ['data-dice-formula-row','data-dice-drop-position','data-dice-drop-indicator','data-dice-drag-ghost']) assert.ok(row.includes(hook));
for(const text of ['Sposta su','Sposta giù','INTERACTIVE_DRAG_SELECTOR','input, select, button','setDragImage','event.clientY','getBoundingClientRect()','<option value="equal">Uguale</option>','ariaLabel="Soglia Mantieni"','data-dice-custom-formula-select']) assert.ok(row.includes(text),`missing ${text}`);
for(const hook of ['data-dice-roll-builder','data-dice-save-formula','data-dice-clear-builder','data-dice-new-folder']) assert.ok(panel.includes(hook));
for(const hook of ['data-saved-dice-formula','data-dice-visibility-toggle','data-dice-formula-edit','data-dice-formula-duplicate','data-dice-formula-delete']) assert.ok(saved.includes(hook));
for(const hook of ['data-dice-history-drawer','data-dice-history-scroll','data-dice-history-scrollbar-track','data-dice-history-scrollbar-thumb','data-dice-3d-toggle','data-dice-history-clear']) assert.ok(history.includes(hook));
assert.ok(history.includes('Pulisci')); assert.ok(history.includes('scrollContainer.scrollTop = scrollContainer.scrollHeight')); assert.ok(history.includes('max-h-[58vh]')); assert.ok(history.includes('min-w-[18rem]')); assert.ok(history.includes('max-w-[min(24rem,calc(100vw-8rem))]')); assert.ok(history.includes('<DiceQuickRollFloating />'));
assert.ok(card.includes('formatPrimaryRollResult(result)')); assert.ok(card.includes('data-dice-player-actions')); assert.ok(card.includes('data-dice-reroll')); assert.ok(card.includes("result.visibility === 'secret'")); assert.ok(card.includes('Segreto')); assert.ok(card.includes('CustomDieFaceResult'));
assert.ok(card.includes("import { DiceTypeIcon } from './DiceTypeIcon';"), 'dice history must reuse the matching standard die artwork');
assert.ok(card.includes('CHAT_DIE_SIDES = [4, 6, 8, 10, 12, 20, 100]'), 'dice history must recognize every standard Hollowgate die shape');
assert.ok(card.includes('className="h-[20px] w-[20px]"'), 'custom die face results must use the larger chat icon size');
assert.ok(card.includes("h-[20px] !gap-px [&>img]:!h-[20px] [&>img]:!w-[20px]"), 'd100 dice pair must match the 20px chat die height');
assert.ok(card.includes('<StandardDieResult sides={die.sides} face={die.face} contribution={die.contribution}/>'), 'standard numeric results must render their specific die icon');
assert.ok(!card.includes('<Dices className="h-2.5 w-2.5"/>d{die.sides}:'), 'standard numeric results must not use the generic two-dice icon plus dXX label');
for(const hook of ['data-dice-quick-roll-floating','data-dice-quick-toggle','data-dice-history-toggle','data-dice-history-unread','data-dice-quick-palette']) assert.ok(quick.includes(hook));
for(const hook of ['data-custom-die-configurator','data-custom-die-face','data-custom-die-upload','data-custom-die-face-drag-source','data-custom-die-face-drop-target']) assert.ok(custom.includes(hook));
assert.ok(custom.includes("e.dataTransfer.effectAllowed='copy'"),'custom face preview drag must advertise copy semantics');
assert.ok(custom.includes("e.dataTransfer.dropEffect='copy'"),'custom face drop target must use copy semantics');
assert.ok(custom.includes('copyFaceVisual(source,pos)'),'dropping a custom face must copy its visual to the target');
assert.ok(custom.includes('draggable={false} data-custom-die-image-preview'),'image contents must not start their own native image drag');
assert.ok(custom.includes('!isCustomDieImageAssetUsed(next,previous.assetPath)'),'shared uploaded images must only be removed when no face still references them');
assert.ok(customDie.includes('export function copyCustomDieFaceVisual'),'custom die visual copying must be isolated in a reusable helper');
assert.ok(customDie.includes('? { ...face, visual: { ...source.visual } as CustomDieFaceVisual }'),'copying a visual must preserve target face metadata');
console.log('Dice UI verification passed.');
