import assert from 'node:assert/strict';
import fs from 'node:fs';
import { boostDice3DSpin,DICE_3D_SPIN_MULTIPLIER,DICE_3D_THROW_STRENGTH } from '../src/app/components/session/dice/dice3dMotion.ts';
import { projectRollTo3D } from '../src/app/components/session/dice/dice3dProjection.ts';
import type { CustomDieRollSnapshot,DiceAppearance,RollDiceGroup,RollResult } from '../src/app/components/session/dice/diceTypes.ts';
function group(itemId:string,sides:number,faces:number[],appearance?:DiceAppearance):RollDiceGroup{const rolls=faces.map((face,index)=>({id:`${itemId}-${index}`,groupItemId:itemId,sides,face,contribution:face,active:true,source:'base' as const,explosionDepth:0,chainId:`${itemId}-${index}`}));return{itemId,sides,requestedQuantity:faces.length,rolls,activeRollIds:rolls.map(r=>r.id),contribution:faces.reduce((a,b)=>a+b,0),appearance}}
function result(groups:RollDiceGroup[]):RollResult{return{id:'r',campaignId:'c',rollerId:'u',rollerName:'T',formulaName:'3D',formulaText:'test',visibility:'public',sourceItems:[],diceGroups:groups,arithmeticSteps:[],comparisons:[],total:0,createdAt:1}}
const simple=projectRollTo3D(result([group('d20',20,[17,4])]));assert.deepEqual(simple.map(c=>({sides:c.sides,values:c.values,notation:c.notation})),[{sides:20,values:[17,4],notation:'2d20@17,4'}]);
const standard=projectRollTo3D(result([group('d4',4,[3]),group('d6',6,[6]),group('d8',8,[7]),group('d10',10,[9]),group('d12',12,[11]),group('d20',20,[19]),group('d100',100,[73])]));assert.deepEqual(standard.map(c=>c.notation),['1d4@3','1d6@6','1d8@7','1d10@9','1d12@11','1d20@19','1d100@70','1d10@3']);
const arcane:DiceAppearance={bodyColor:'#223344',symbolColor:'#ffeedd',skinId:'arcane',effectsEnabled:true};const styledD100=projectRollTo3D(result([group('styled-100',100,[73],arcane)]));assert.equal(styledD100.length,2);for(const chunk of styledD100){assert.equal(chunk.appearances?.length,1);assert.deepEqual(chunk.appearances?.[0]?.appearance,arcane);assert.equal(chunk.appearances?.[0]?.custom,false)}
const snap:CustomDieRollSnapshot={id:'custom',name:'Custom',sides:6,faces:Array.from({length:6},(_,i)=>({index:i+1,role:'single',visual:{kind:'icon',iconName:'Star'},numericValue:null})),bodyColor:'#111111',symbolColor:'#ffffff',skinId:'fire',effectsEnabled:true};
const baseCustom=group('custom',6,[2,5]);const customGroup:RollDiceGroup={...baseCustom,customDieId:'custom',customDieName:'Custom',customDieSnapshot:snap,rolls:baseCustom.rolls.map((r,i)=>({...r,customDieId:'custom',customFace:snap.faces[i?4:1],physicalRole:'single',logicalRollIndex:i,contribution:null})),contribution:null};const projected=projectRollTo3D(result([customGroup]));assert.deepEqual(projected.map(c=>c.values),[[2],[5]]);assert.ok(projected.every(c=>c.customMaterials?.[0]?.customDie.id==='custom'));assert.ok(projected.every(c=>c.appearances?.[0]?.appearance.skinId==='fire'&&c.appearances?.[0]?.custom===true));
const imageSnap:CustomDieRollSnapshot={...snap,id:'image-custom',faces:snap.faces.map((face,index)=>index===0?{...face,visual:{kind:'image' as const,assetPath:'p',publicUrl:'https://example.invalid/image.webp'}}:face)};const imageBase=group('image-custom',6,[1]);const imageGroup:RollDiceGroup={...imageBase,customDieId:imageSnap.id,customDieSnapshot:imageSnap,rolls:imageBase.rolls.map(r=>({...r,customDieId:imageSnap.id,customFace:imageSnap.faces[0],physicalRole:'single' as const,logicalRollIndex:0,contribution:null})),contribution:null};assert.equal(projectRollTo3D(result([imageGroup]))[0]?.appearances?.[0]?.preserveFaceColors,true);
const d4Snap:CustomDieRollSnapshot={...snap,id:'custom-d4',sides:4,faces:Array.from({length:4},(_,i)=>({index:i+1,role:'single' as const,visual:{kind:'icon' as const,iconName:'Star'},numericValue:null}))};const d4Rolls=group('custom-d4',4,[3]).rolls.map(r=>({...r,customDieId:'custom-d4',customFace:d4Snap.faces[2],physicalRole:'single' as const,logicalRollIndex:0,contribution:null}));const customD4Group:RollDiceGroup={itemId:'custom-d4',sides:4,requestedQuantity:1,rolls:d4Rolls,activeRollIds:d4Rolls.map(r=>r.id),contribution:null,customDieId:'custom-d4',customDieName:'Custom d4',customDieSnapshot:d4Snap};const customD4Projected=projectRollTo3D(result([customD4Group]));assert.deepEqual(customD4Projected.map(c=>c.notation),['1d4@3']);assert.equal(customD4Projected[0]?.customMaterials?.[0]?.customDie.id,'custom-d4');
const d100Snap:CustomDieRollSnapshot={...snap,id:'p',sides:100,faces:[...Array.from({length:10},(_,i)=>({index:i+1,role:'tens' as const,visual:{kind:'icon' as const,iconName:'Star'},numericValue:null})),...Array.from({length:10},(_,i)=>({index:i+1,role:'units' as const,visual:{kind:'icon' as const,iconName:'Star'},numericValue:null}))]};const pair:RollDiceGroup={itemId:'p',sides:100,requestedQuantity:1,rolls:[{id:'t',groupItemId:'p',sides:100,face:4,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'c',customDieId:'p',customFace:d100Snap.faces[3],physicalRole:'tens',logicalRollIndex:0},{id:'u',groupItemId:'p',sides:10,face:7,contribution:null,active:true,source:'base',explosionDepth:0,chainId:'c',customDieId:'p',customFace:d100Snap.faces[16],physicalRole:'units',logicalRollIndex:0}],activeRollIds:['t','u'],contribution:null,customDieId:'p',customDieSnapshot:d100Snap};assert.deepEqual(projectRollTo3D(result([pair])).map(c=>c.notation),['1d100@40','1d10@7']);
assert.equal(DICE_3D_THROW_STRENGTH,1.4);assert.equal(DICE_3D_SPIN_MULTIPLIER,1.2);const motion={vectors:[{angle:{x:5,y:-10,z:0}},{angle:{x:0,y:0,z:0}},{}]};assert.equal(boostDice3DSpin(motion),motion);assert.deepEqual(motion.vectors[0].angle,{x:6,y:-12,z:0});
const read=(p:string)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');const renderer=read('src/app/components/session/dice/dice3dRenderer.ts');const materials=read('src/app/components/session/dice/dice3dCustomMaterials.ts');const appearance=read('src/app/components/session/dice/dice3dAppearanceMaterials.ts');const textures=read('src/app/components/session/dice/dice3dSkinTextures.ts');const effects=read('src/app/components/session/dice/dice3dSkinEffects.ts');
assert.ok(renderer.includes("await import('@3d-dice/dice-box-threejs')"));assert.equal((renderer.match(/this\.box\.roll\(/g)??[]).length,1);assert.ok(renderer.includes('installDiceAppearanceAdapter'));assert.ok(renderer.includes('installCustomDiceMaterialAdapter'));assert.ok(renderer.indexOf('installDiceAppearanceAdapter')<renderer.indexOf('installCustomDiceMaterialAdapter'),'appearance adapter must be installed before the Custom label adapter');assert.ok(renderer.includes('installDice3DSpinAdapter(box)'));assert.ok(renderer.includes('strength: DICE_3D_THROW_STRENGTH'));assert.ok(renderer.includes('finally'));assert.ok(renderer.includes("signal.addEventListener('abort', stopEffectsOnAbort, { once: true })")&&renderer.includes("signal.removeEventListener('abort', stopEffectsOnAbort)"),'skin effect lifecycle must stop immediately on abort');
assert.ok(materials.includes('ICON_DATA'));assert.ok(materials.includes('physicalSides === 4'));assert.ok(materials.includes('buildSimultaneousMaterialQueue'));assert.ok(materials.includes('swapDiceFace_D4'),'custom d4 must keep the upstream forced-face material remap interception');assert.ok(materials.includes('customD4Meshes = new WeakMap'),'custom d4 forced remap must retain per-mesh descriptors');assert.ok(materials.includes('originalSetMaterialInfo?.();'),'custom d4 forced remap must rebuild valid randomized material state');assert.ok(materials.includes('applyCustomFactoryMaterialState(typedFactory, ready.descriptor)'),'custom d4 forced remap must reapply its exact custom colors/textures');
assert.ok(appearance.includes('buildSimultaneousAppearanceQueue'));assert.ok(appearance.includes('getDice3DTextureDescriptor(appearance)'));assert.ok(appearance.includes("console.error('Texture skin 3D non disponibile, uso il materiale neutro:'"),'skin texture failures must fall back to neutral material');assert.ok(appearance.includes('descriptor.preserveFaceColors'),'appearance adapter must not emissively tint uploaded Custom image faces');assert.ok(appearance.includes('swapDiceFace_D4'),'general appearance must survive d4 forced-result remaps');
for(const skin of ['fire','ice','lightning','poison','stone','metal','obsidian','arcane'])assert.ok(textures.includes(`case '${skin}'`),`missing deterministic 3D texture for ${skin}`);assert.ok(!/https?:\/\//.test(textures),'3D skins must not depend on remote texture assets');assert.ok(effects.includes("window.matchMedia?.('(prefers-reduced-motion: reduce)').matches"));assert.ok(effects.includes('window.requestAnimationFrame'));assert.ok(effects.includes('window.cancelAnimationFrame'));assert.ok(effects.includes('if (this.raf !== null || this.entries.length === 0) return;'),'one shared RAF loop must serve the entire roll');assert.ok(effects.includes('preserveFaceColors'),'animated emissive effects must respect untinted Custom image faces');
console.log('Dice 3D verification passed.');
