import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.108.1";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const DICE_SKINS=new Set(["none","fire","ice","lightning","poison","stone","metal","obsidian","arcane"]);
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value)}
function isNullableFinite(value:unknown){return value===null||(typeof value==="number"&&Number.isFinite(value))}
function isDiceAppearance(value:unknown){return isRecord(value)&&typeof value.bodyColor==="string"&&typeof value.symbolColor==="string"&&typeof value.skinId==="string"&&DICE_SKINS.has(value.skinId)&&typeof value.effectsEnabled==="boolean"}
function isCustomFace(value:unknown){if(!isRecord(value))return false;if(typeof value.index!=="number"||!Number.isInteger(value.index)||value.index<1)return false;if(value.role!=="single"&&value.role!=="tens"&&value.role!=="units")return false;if(value.numericValue!==null&&value.numericValue!==undefined&&(typeof value.numericValue!=="number"||!Number.isFinite(value.numericValue)))return false;if(!isRecord(value.visual))return false;if(value.visual.kind==="icon")return typeof value.visual.iconName==="string"&&value.visual.iconName.length>0;if(value.visual.kind==="image")return typeof value.visual.assetPath==="string"&&value.visual.assetPath.length>0&&typeof value.visual.publicUrl==="string"&&value.visual.publicUrl.length>0;if(value.visual.kind==="text")return typeof value.visual.text==="string"&&value.visual.text.trim().length>0;return false}
function isCustomDieSnapshot(value:unknown){if(!isRecord(value))return false;if(typeof value.id!=="string"||typeof value.name!=="string"||typeof value.sides!=="number")return false;if(!Array.isArray(value.faces)||!value.faces.every(isCustomFace))return false;if(typeof value.bodyColor!=="string"||typeof value.symbolColor!=="string")return false;if(value.skinId!==undefined&&(typeof value.skinId!=="string"||!DICE_SKINS.has(value.skinId)))return false;if(value.effectsEnabled!==undefined&&typeof value.effectsEnabled!=="boolean")return false;return true}
function isRollDiePayload(value:unknown){if(!isRecord(value))return false;if(typeof value.id!=="string"||!value.id.length)return false;if(typeof value.groupItemId!=="string"||!value.groupItemId.length)return false;if(typeof value.sides!=="number"||!Number.isFinite(value.sides))return false;if(typeof value.face!=="number"||!Number.isFinite(value.face))return false;if(!isNullableFinite(value.contribution))return false;if(typeof value.active!=="boolean")return false;if(value.keepMatched!==undefined&&typeof value.keepMatched!=="boolean")return false;if(value.customDieId!==undefined&&typeof value.customDieId!=="string")return false;if(value.physicalRole!==undefined&&value.physicalRole!=="single"&&value.physicalRole!=="tens"&&value.physicalRole!=="units")return false;if(value.logicalRollIndex!==undefined&&(!Number.isInteger(value.logicalRollIndex)||Number(value.logicalRollIndex)<0))return false;if(value.customFace!==undefined&&!isCustomFace(value.customFace))return false;return true}
function isDiceGroupPayload(value:unknown){if(!isRecord(value)||typeof value.itemId!=="string"||!Array.isArray(value.rolls)||!value.rolls.every(isRollDiePayload)||!Array.isArray(value.activeRollIds)||!value.activeRollIds.every(id=>typeof id==="string")||!isNullableFinite(value.contribution))return false;if(value.appearance!==undefined&&!isDiceAppearance(value.appearance))return false;if(value.customDieSnapshot!==undefined&&!isCustomDieSnapshot(value.customDieSnapshot))return false;return true}
function isArithmeticStepPayload(value:unknown){if(!isRecord(value))return false;if(typeof value.itemId!=="string"||!value.itemId.length)return false;if(value.scope !== 'dice' && value.scope !== 'total')return false;if(value.scope==='dice'&&(typeof value.groupItemId!=="string"||!value.groupItemId.length))return false;if(value.scope==='total'&&value.groupItemId!==undefined)return false;if(typeof value.before!=="number"||!Number.isFinite(value.before)||typeof value.after!=="number"||!Number.isFinite(value.after))return false;return true}
function isRollResultPayload(value:unknown):value is Record<string,unknown>&{id:string;campaignId:string;rollerId:string;rollerName:string;formulaName:string;formulaText:string;visibility:"secret";total:number|null;createdAt:number}{if(!isRecord(value))return false;for(const key of ["id","campaignId","rollerId","rollerName","formulaName","formulaText"] as const){if(typeof value[key]!=="string"||!value[key].length)return false}if(value.visibility!=="secret")return false;if(!isNullableFinite(value.total))return false;if(typeof value.createdAt!=="number"||!Number.isFinite(value.createdAt))return false;if(!Array.isArray(value.sourceItems)||!Array.isArray(value.diceGroups)||!value.diceGroups.every(isDiceGroupPayload)||!Array.isArray(value.arithmeticSteps)||!value.arithmeticSteps.every(isArithmeticStepPayload)||!Array.isArray(value.comparisons))return false;return true}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed"},405);const supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!supabaseUrl||!serviceRoleKey)return json({error:"Server configuration error"},500);const authorization=req.headers.get("Authorization")??"",token=authorization.startsWith("Bearer ")?authorization.slice(7):"";if(!token)return json({error:"Missing authorization"},401);const admin=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data:{user},error:userError}=await admin.auth.getUser(token);if(userError||!user)return json({error:"Unauthorized"},401);let body:unknown;try{body=await req.json()}catch{return json({error:"Invalid JSON"},400)}if(!isRecord(body)||typeof body.campaignId!=="string"||!isRollResultPayload(body.result))return json({error:"Invalid dice roll payload"},400);const campaignId=body.campaignId,result=body.result;if(result.campaignId!==campaignId)return json({error:"Campaign mismatch"},400);if(result.visibility !== 'secret')return json({error:"Only secret rolls may use this relay"},400);if(result.rollerId !== user.id)return json({error:"Roller mismatch"},403);const{data:campaign,error:campaignError}=await admin.from('campaigns').select('owner_profile_id').eq('id',campaignId).is('deleted_at',null).maybeSingle();if(campaignError)return json({error:"Campaign lookup failed"},500);if(!campaign)return json({error:"Campaign not found"},404);const ownerProfileId=String(campaign.owner_profile_id);if(ownerProfileId === user.id)return json({error:"GM secret rolls must remain local"},400);const{data:membership,error:membershipError}=await admin.from('campaign_members').select('campaign_id').eq('campaign_id',campaignId).eq('profile_id',user.id).maybeSingle();if(membershipError)return json({error:"Membership lookup failed"},500);if(!membership)return json({error:"Not a campaign member"},403);await admin.realtime.setAuth(serviceRoleKey);const channel=admin.channel(`profile:${ownerProfileId}`,{config:{private:true}});try{const response=await channel.httpSend('dice_roll', result);if(response.success===false)return json({error:"Realtime relay failed"},502)}finally{await admin.removeChannel(channel)}return json({ok:true})});
