import { useMemo, useRef, useState } from 'react';
import { ImagePlus, Save, Shapes, Type, X } from 'lucide-react';
import { toast } from 'sonner';
import { NoteIconGrid, NoteIconGlyph } from '../shared/NoteIconGrid';
import { Popover, PopoverContent, PopoverTrigger } from '../../ui/popover';
import { Switch } from '../../ui/switch';
import { Tooltip, TooltipContent, TooltipTrigger } from '../../ui/tooltip';
import { CustomDieTextFace } from './CustomDieTextFace';
import { DiceSkinSurface } from './DiceSkinSurface';
import { DiceNumericStepper } from './DiceNumericStepper';
import { copyCustomDieFaceVisual, expectedCustomDieFaceCount, getCustomDieQuickRollMax, isCustomDieImageAssetUsed, MAX_CUSTOM_DIE_SIDES, MIN_CUSTOM_DIE_SIDES, normalizeCustomDieDefinitionMode, normalizeCustomDieFaceTextInput, validateCustomDieDefinition } from './diceCustomDie.ts';
import { ensureCustomDieLibraryIconDefaults, toggleCustomDieLibraryIconFace } from './diceCustomDieLibraryIcon.ts';
import { DICE_SKINS } from './diceSkins.ts';
import { MAX_DICE_TEXTURE_SCALE, MIN_DICE_TEXTURE_SCALE, normalizeDiceTextureScale } from './diceTextureScale.ts';
import { removeDiceFaceAsset, uploadDiceFaceAsset } from '../../../../services/supabase/diceFaceAssetService';
import type { CustomDieDefinitionMode, CustomDieFace, CustomDieFaceVisual, CustomDieResultMode, CustomDieSides, DiceSkinId, SavedCustomDie, StandardDieSides } from './diceTypes.ts';

const FIXED_SIDES: Exclude<StandardDieSides, 100>[] = [4, 6, 8, 10, 12, 20];

function blankFaces(sides: CustomDieSides): CustomDieFace[] {
  if (sides === 100) {
    return [
      ...Array.from({ length: 10 }, (_, i) => ({ index: i + 1, role: 'tens' as const, visual: { kind: 'icon' as const, iconName: 'Star' }, label: '', numericValue: null, isLibraryIcon: i === 0 })),
      ...Array.from({ length: 10 }, (_, i) => ({ index: i + 1, role: 'units' as const, visual: { kind: 'icon' as const, iconName: 'Star' }, label: '', numericValue: null, isLibraryIcon: i === 0 })),
    ];
  }
  return Array.from({ length: sides }, (_, i) => ({ index: i + 1, role: 'single' as const, visual: { kind: 'icon' as const, iconName: 'Star' }, label: '', numericValue: null }));
}

export function CustomDieConfigurator({ campaignId, ownerProfileId, initial, onSave, onCancel }: {
  campaignId: string; ownerProfileId: string; initial?: SavedCustomDie | null;
  onSave: (draft: { id: string; name: string; sides: CustomDieSides; quickRollQuantity: number; definitionMode: CustomDieDefinitionMode; resultDisplayMode: CustomDieResultMode; faces: CustomDieFace[]; bodyColor: string; symbolColor: string; skinId: DiceSkinId; effectsEnabled: boolean; textureScale: number }) => Promise<void>;
  onCancel: () => void;
}) {
  const pendingAssets = useRef(new Set<string>());
  const [id] = useState(() => initial?.id ?? crypto.randomUUID());
  const [name, setName] = useState(initial?.name ?? 'Nuovo dado Custom');
  const [sides, setSides] = useState<CustomDieSides>(initial?.sides ?? 6);
  const [definitionMode, setDefinitionMode] = useState<CustomDieDefinitionMode>(() => normalizeCustomDieDefinitionMode(initial?.definitionMode));
  const [customGeometry, setCustomGeometry] = useState(() => Boolean(initial && (initial.definitionMode === 'numeric' || ![4, 6, 8, 10, 12, 20, 100].includes(initial.sides))));
  const [customSidesDraft, setCustomSidesDraft] = useState(() => String(initial?.sides ?? 6));
  const [quickRollQuantity, setQuickRollQuantity] = useState(() => initial?.quickRollQuantity ?? 1);
  const [resultDisplayMode, setResultDisplayMode] = useState<CustomDieResultMode>(initial?.resultDisplayMode ?? 'single');
  const [faces, setFaces] = useState<CustomDieFace[]>(() => initial ? ensureCustomDieLibraryIconDefaults(initial.faces.map((face) => ({ ...face, visual: { ...face.visual } }))) : blankFaces(6));
  const facesRef = useRef(faces); facesRef.current = faces;
  const dragSourceFace = useRef<number | null>(null);
  const [dragTargetFace, setDragTargetFace] = useState<number | null>(null);
  const [bodyColor, setBodyColor] = useState(initial?.bodyColor ?? '#20242f');
  const [symbolColor, setSymbolColor] = useState(initial?.symbolColor ?? '#ffffff');
  const [skinId, setSkinId] = useState<DiceSkinId>(initial?.skinId ?? 'none');
  const [effectsEnabled, setEffectsEnabled] = useState(initial?.effectsEnabled ?? false);
  const [textureScale, setTextureScale] = useState(() => normalizeDiceTextureScale(initial?.textureScale));
  const [iconFace, setIconFace] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);
  const validation = useMemo(() => validateCustomDieDefinition({ name, sides, definitionMode, resultDisplayMode, faces } as SavedCustomDie), [name, sides, definitionMode, resultDisplayMode, faces]);
  const hasSymbolFaces = faces.some((face) => face.visual.kind === 'icon' || face.visual.kind === 'text');
  const hasImageFaces = faces.some((face) => face.visual.kind === 'image');
  const appearance = { bodyColor, symbolColor, skinId, effectsEnabled, textureScale };

  const removePending = async (path: string) => { if (!pendingAssets.current.has(path)) return; pendingAssets.current.delete(path); try { await removeDiceFaceAsset(path); } catch (error) { console.error(error); } };
  const cancel = () => { for (const path of pendingAssets.current) void removeDiceFaceAsset(path); pendingAssets.current.clear(); onCancel(); };
  const changeSides = (next: CustomDieSides, nextMode: CustomDieDefinitionMode) => { if (next === sides && nextMode === definitionMode) return; const becomingNumeric = nextMode === 'numeric' && faces.length > 0; const changingFaceGeometry = nextMode === 'faces' && faces.some((face) => face.visual.kind === 'image'); if (becomingNumeric && !confirm('Oltre 20 facce il dXX è solo numerico. Le personalizzazioni delle facce verranno rimosse. Continuare?')) return; if (!becomingNumeric && changingFaceGeometry && !confirm('Cambiare geometria rimuoverà le immagini già assegnate alle facce. Continuare?')) return; for (const face of faces) if (face.visual.kind === 'image') void removePending(face.visual.assetPath); const nextFaces = nextMode === 'numeric' ? [] : blankFaces(next); facesRef.current = nextFaces; setSides(next); setDefinitionMode(nextMode); if (nextMode === 'numeric') setResultDisplayMode('single'); setQuickRollQuantity((value) => Math.min(value, getCustomDieQuickRollMax({ sides: next, definitionMode: nextMode }))); setFaces(nextFaces); };
  const applyCustomSides = () => { const parsed = Number.parseInt(customSidesDraft, 10); const next = Math.min(MAX_CUSTOM_DIE_SIDES, Math.max(MIN_CUSTOM_DIE_SIDES, Number.isFinite(parsed) ? parsed : sides)); setCustomSidesDraft(String(next)); changeSides(next, next > 20 ? 'numeric' : 'faces'); };
  const patchFace = (pos: number, patch: Partial<CustomDieFace>) => setFaces((current) => { const next = current.map((face, index) => index === pos ? { ...face, ...patch } : face); facesRef.current = next; return next; });
  const stepFaceValue = (pos: number, delta: number) => { const current = facesRef.current[pos]?.numericValue; patchFace(pos, { numericValue: (current ?? 0) + delta }); };
  const replaceFaceVisual = (pos: number, visual: CustomDieFaceVisual) => { const current = facesRef.current; const previous = current[pos]?.visual; if (!previous) return; const next = current.map((face, index) => index === pos ? { ...face, visual: { ...visual } } : face); facesRef.current = next; setFaces(next); if (previous.kind === 'image' && (visual.kind !== 'image' || visual.assetPath !== previous.assetPath) && !isCustomDieImageAssetUsed(next, previous.assetPath)) void removePending(previous.assetPath); };
  const copyFaceVisual = (sourcePos: number, targetPos: number) => { if (sourcePos === targetPos) return; const current = facesRef.current; const previous = current[targetPos]?.visual; const next = copyCustomDieFaceVisual(current, sourcePos, targetPos); facesRef.current = next; setFaces(next); if (previous?.kind === 'image' && !isCustomDieImageAssetUsed(next, previous.assetPath)) void removePending(previous.assetPath); };
  const toggleLibraryIconFace = (pos: number) => { const next = toggleCustomDieLibraryIconFace(facesRef.current, pos); facesRef.current = next; setFaces(next); };
  const faceVisualButtonClass = (selected: boolean) => `flex h-8 flex-1 items-center justify-center rounded-md border transition-colors ${selected ? 'border-[var(--dash-accent)] bg-[var(--dash-surface-2)] text-[var(--dash-accent)]' : 'border-[var(--dash-border)] text-[var(--dash-text)] hover:bg-[var(--dash-surface-2)]'}`;

  return <div className="fixed inset-0 z-[1200] flex items-center justify-center bg-black/60 p-4 caret-transparent" data-custom-die-configurator><div className="flex max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-[var(--dash-border)] bg-[var(--dash-panel)] shadow-2xl">
    <header className="flex items-center gap-3 border-b border-[var(--dash-border)] p-4"><div className="min-w-0 flex-1"><div className="text-lg font-semibold text-[var(--dash-text-strong)]">Dado Custom</div><div className="text-xs text-[var(--dash-muted)]">{definitionMode === 'numeric' ? `d${sides} numerico` : `${expectedCustomDieFaceCount(sides)} facce fisiche configurabili`}</div></div><button onClick={cancel} className="rounded p-2 text-[var(--dash-muted)] hover:bg-[var(--dash-surface-2)]"><X className="h-4 w-4" /></button></header>
    <div data-custom-die-configurator-scroll className="custom-die-configurator-scroll grid min-h-0 flex-1 items-start gap-4 overflow-y-auto p-4 lg:grid-cols-[260px_1fr]"><aside className="space-y-4">
      <label className="block text-xs text-[var(--dash-muted)]">Nome<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-lg border border-[var(--dash-border)] bg-[var(--dash-input)] px-3 py-2 text-sm text-[var(--dash-text)] outline-none [caret-color:auto]" /></label>
      <div><div className="mb-1 text-xs text-[var(--dash-muted)]">Geometria</div><div className="flex flex-wrap gap-1">{FIXED_SIDES.map((value) => <button key={value} onClick={() => { setCustomGeometry(false); changeSides(value, 'faces'); }} className={`rounded-md border px-2 py-1 text-xs ${!customGeometry && value === sides ? 'border-[var(--dash-accent)] bg-[var(--dash-surface-2)] text-[var(--dash-text-strong)]' : 'border-[var(--dash-border)] text-[var(--dash-muted)]'}`}>d{value}</button>)}<button type="button" data-custom-die-dxx onClick={() => { setCustomGeometry(true); setCustomSidesDraft(String(sides)); }} className={`rounded-md border px-2 py-1 text-xs ${customGeometry ? 'border-[var(--dash-accent)] bg-[var(--dash-surface-2)] text-[var(--dash-text-strong)]' : 'border-[var(--dash-border)] text-[var(--dash-muted)]'}`}>dXX</button><button type="button" onClick={() => { setCustomGeometry(false); changeSides(100, 'faces'); }} className={`rounded-md border px-2 py-1 text-xs ${!customGeometry && sides === 100 ? 'border-[var(--dash-accent)] bg-[var(--dash-surface-2)] text-[var(--dash-text-strong)]' : 'border-[var(--dash-border)] text-[var(--dash-muted)]'}`}>d100</button></div>{customGeometry && <label data-custom-die-dxx-sides className="mt-2 block text-[10px] text-[var(--dash-muted)]">Numero di facce<input autoFocus type="number" min={MIN_CUSTOM_DIE_SIDES} max={MAX_CUSTOM_DIE_SIDES} step={1} value={customSidesDraft} onChange={(event) => setCustomSidesDraft(event.target.value)} onBlur={applyCustomSides} onKeyDown={(event) => { if (event.key === 'Enter') event.currentTarget.blur(); }} className="mt-1 w-full rounded-md border border-[var(--dash-border)] bg-[var(--dash-input)] px-2 py-1.5 text-center text-sm text-[var(--dash-text)] outline-none [caret-color:auto]" /><span className="mt-1 block">Da {MIN_CUSTOM_DIE_SIDES} a {MAX_CUSTOM_DIE_SIDES}. Oltre 20: solo risultati numerici, senza facce personalizzate.</span></label>}</div>
      <div data-custom-die-quick-roll-quantity><div className="mb-1 text-xs text-[var(--dash-muted)]">Quantità tiro rapido</div><DiceNumericStepper value={quickRollQuantity} min={1} max={getCustomDieQuickRollMax({ sides, definitionMode })} integer fullWidth ariaLabel="Quantità tiro rapido" onChange={setQuickRollQuantity} /></div>
      {definitionMode === 'faces' ? <fieldset data-custom-die-result-mode><legend className="mb-1 text-xs text-[var(--dash-muted)]">Visualizzazione risultati</legend><div className="grid grid-cols-2 gap-1 rounded-lg border border-[var(--dash-border)] bg-[var(--dash-surface)] p-1">{([{ value: 'single', label: 'Singoli' }, { value: 'grouped', label: 'In gruppo' }] as const).map((option) => <label key={option.value} className={`flex cursor-pointer items-center justify-center gap-1.5 rounded-md px-2 py-1.5 text-xs transition-colors ${resultDisplayMode === option.value ? 'bg-[var(--dash-surface-2)] font-semibold text-[var(--dash-text-strong)]' : 'text-[var(--dash-muted)] hover:text-[var(--dash-text)]'}`}><input type="radio" name={`custom-die-result-mode-${id}`} value={option.value} checked={resultDisplayMode === option.value} onChange={() => setResultDisplayMode(option.value)} className="accent-[var(--dash-accent)]" />{option.label}</label>)}</div></fieldset> : <div data-custom-die-numeric-mode className="rounded-lg border border-[var(--dash-border)] bg-[var(--dash-surface)] p-2 text-xs text-[var(--dash-muted)]">Le facce da 1 a {sides} sono numeriche. Questa geometria non viene simulata in 3D.</div>}
      <label className="block text-xs text-[var(--dash-muted)]">Colore corpo<input type="color" value={bodyColor} onChange={(event) => setBodyColor(event.target.value)} className="mt-1 h-9 w-full" /></label>
      <label className={`block text-xs text-[var(--dash-muted)] ${!hasSymbolFaces ? 'opacity-50' : ''}`}>Colore simboli<input type="color" value={symbolColor} disabled={!hasSymbolFaces} onChange={(event) => setSymbolColor(event.target.value)} className="mt-1 h-9 w-full disabled:cursor-not-allowed" />{hasImageFaces && <span className="mt-1 block text-[10px] text-[var(--dash-muted)]">Utilizzabile per icone e testo</span>}</label>
      {!validation.valid && <div className="rounded-lg border border-red-500/40 bg-red-500/10 p-2 text-xs text-red-300">{validation.issues.join(' ')}</div>}
    </aside>
    <section className="min-w-0 space-y-4">{definitionMode === 'numeric' ? <div data-custom-die-numeric-preview className="flex min-h-48 items-center justify-center rounded-xl border border-[var(--dash-border)] bg-[var(--dash-surface)]"><div className="text-center"><div className="text-5xl font-bold text-[var(--dash-text-strong)]">d{sides}</div><div className="mt-2 text-sm text-[var(--dash-muted)]">Risultati numerici da 1 a {sides}</div></div></div> : <div className="grid content-start auto-rows-max gap-2 sm:grid-cols-2 xl:grid-cols-3">{faces.map((face, pos) => { const faceLabel = sides === 100 ? `${face.role === 'tens' ? 'Decine' : 'Unità'} ${face.index}` : `Faccia ${face.index}`; return <div key={`${face.role}:${face.index}`} data-custom-die-face data-custom-die-face-drop-target={dragTargetFace === pos ? 'true' : undefined} onDragOver={(event) => { const source = dragSourceFace.current; if (source === null || source === pos) return; event.preventDefault(); event.dataTransfer.dropEffect = 'copy'; if (dragTargetFace !== pos) setDragTargetFace(pos); }} onDrop={(event) => { event.preventDefault(); const source = dragSourceFace.current; if (source !== null && source !== pos) copyFaceVisual(source, pos); setDragTargetFace(null); }} className={`self-start rounded-xl border bg-[var(--dash-surface)] p-3 transition-shadow ${dragTargetFace === pos ? 'border-[var(--dash-accent)] ring-2 ring-[var(--dash-accent)]/30' : 'border-[var(--dash-border)]'}`}>
      <div className="mb-2 flex items-center justify-between"><div className="flex min-w-0 items-center gap-1.5"><Tooltip><TooltipTrigger asChild><button type="button" role="radio" aria-checked={face.isLibraryIcon === true} aria-label={face.isLibraryIcon ? `Rimuovi ${faceLabel} come icona del dado Custom` : `Usa ${faceLabel} come icona del dado Custom`} data-custom-die-library-icon-radio onClick={() => toggleLibraryIconFace(pos)} className={`flex h-4 w-4 shrink-0 items-center justify-center rounded-full border ${face.isLibraryIcon ? 'border-[var(--dash-accent)]' : 'border-[var(--dash-border)]'} hover:border-[var(--dash-accent)]`}>{face.isLibraryIcon && <span className="h-2 w-2 rounded-full bg-[var(--dash-accent)]" />}</button></TooltipTrigger><TooltipContent>{face.isLibraryIcon ? 'Rimuovi questa faccia come icona del dado Custom' : 'Usa questa faccia come icona del dado Custom nella libreria'}</TooltipContent></Tooltip><span className="truncate text-xs font-semibold text-[var(--dash-text-strong)]">{faceLabel}</span></div>
      <Tooltip><TooltipTrigger asChild><span draggable data-custom-die-face-drag-source onDragStart={(event) => { dragSourceFace.current = pos; setDragTargetFace(null); event.dataTransfer.effectAllowed = 'copy'; event.dataTransfer.setData('text/plain', String(pos)); }} onDragEnd={() => { dragSourceFace.current = null; setDragTargetFace(null); }} className="h-8 w-8 cursor-grab active:cursor-grabbing"><DiceSkinSurface appearance={appearance} className="flex h-full w-full items-center justify-center overflow-hidden rounded-md border border-[var(--dash-border)] bg-[var(--dash-input)]"><span className="relative z-10 flex h-full w-full items-center justify-center" style={{ color: symbolColor }}>{face.visual.kind === 'icon' ? <NoteIconGlyph name={face.visual.iconName} className="h-5 w-5 drop-shadow-[0_0_2px_rgba(255,255,255,0.65)]" /> : face.visual.kind === 'text' ? <CustomDieTextFace text={face.visual.text} color={symbolColor} className="h-full w-full drop-shadow-[0_0_2px_rgba(255,255,255,0.65)]" /> : <img draggable={false} data-custom-die-image-preview data-custom-die-image-untinted src={face.visual.publicUrl} className="h-full w-full object-contain p-0.5 drop-shadow-[0_0_2px_rgba(255,255,255,0.65)]" />}</span></DiceSkinSurface></span></TooltipTrigger><TooltipContent>Trascina su un’altra faccia per copiare immagine, icona o testo</TooltipContent></Tooltip></div>
      <div className="flex gap-1"><Popover open={iconFace === pos} onOpenChange={(popoverOpen) => setIconFace(popoverOpen ? pos : null)}><Tooltip><TooltipTrigger asChild><span className="flex flex-1"><PopoverTrigger asChild><button type="button" aria-label="Scegli icona" className={faceVisualButtonClass(face.visual.kind === 'icon')}><Shapes className="h-4 w-4" /></button></PopoverTrigger></span></TooltipTrigger><TooltipContent>Scegli icona</TooltipContent></Tooltip><PopoverContent data-custom-die-icon-picker side="bottom" align="start" sideOffset={6} collisionPadding={12} className="z-[1300] max-h-[70vh] w-[min(22rem,calc(100vw-2rem))] overflow-y-auto border-[var(--dash-border)] bg-[var(--dash-panel)] p-2 text-[var(--dash-text)] shadow-2xl"><NoteIconGrid selectedName={face.visual.kind === 'icon' ? face.visual.iconName : null} onChoose={(iconName) => { replaceFaceVisual(pos, { kind: 'icon', iconName }); setIconFace(null); }} /></PopoverContent></Popover>
      <Tooltip><TooltipTrigger asChild><label aria-label="Carica immagine" className={`${faceVisualButtonClass(face.visual.kind === 'image')} cursor-pointer`}><ImagePlus className="h-4 w-4" /><input data-custom-die-upload type="file" accept="image/*" className="hidden" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { const uploaded = await uploadDiceFaceAsset({ campaignId, ownerProfileId, customDieId: id, file }); pendingAssets.current.add(uploaded.assetPath); replaceFaceVisual(pos, { kind: 'image', ...uploaded }); setIconFace(null); } catch (error) { console.error(error); toast.error(error instanceof Error ? error.message : 'Impossibile caricare l’immagine.'); } finally { setBusy(false); event.currentTarget.value = ''; } }} /></label></TooltipTrigger><TooltipContent>Carica immagine</TooltipContent></Tooltip>
      <Tooltip><TooltipTrigger asChild><button type="button" aria-label="Inserisci testo" data-custom-die-text-select onClick={() => { setIconFace(null); replaceFaceVisual(pos, { kind: 'text', text: face.visual.kind === 'text' ? face.visual.text : '' }); }} className={faceVisualButtonClass(face.visual.kind === 'text')}><Type className="h-4 w-4" /></button></TooltipTrigger><TooltipContent>Inserisci testo</TooltipContent></Tooltip></div>
      {face.visual.kind === 'text' && <textarea data-custom-die-text-input rows={2} placeholder="Testo faccia" value={face.visual.text} onKeyDown={(event) => { if (event.key === 'Enter' && event.currentTarget.value.includes('\n')) event.preventDefault(); }} onChange={(event) => replaceFaceVisual(pos, { kind: 'text', text: normalizeCustomDieFaceTextInput(event.target.value) })} className="mt-2 block h-12 w-full resize-none rounded-md border border-[var(--dash-border)] bg-[var(--dash-input)] px-2 py-1.5 text-center text-xs leading-4 text-[var(--dash-text)] [caret-color:auto]" />}
      <input placeholder="Etichetta" value={face.label ?? ''} onChange={(event) => patchFace(pos, { label: event.target.value })} className="mt-2 w-full rounded-md border border-[var(--dash-border)] bg-[var(--dash-input)] px-2 py-1.5 text-xs text-[var(--dash-text)] [caret-color:auto]" />
      <div data-custom-die-value-stepper className="mt-2 flex items-stretch"><button type="button" data-custom-die-value-increment aria-label="Aumenta valore" onClick={() => stepFaceValue(pos, 1)} className="w-8 shrink-0 rounded-l-md border border-r-0 border-[var(--dash-border)] bg-[var(--dash-input)] text-sm font-semibold text-[var(--dash-text)] hover:bg-[var(--dash-surface-2)]">+</button><input type="number" step="any" placeholder="Valore" value={face.numericValue ?? ''} onChange={(event) => patchFace(pos, { numericValue: event.target.value === '' ? null : Number(event.target.value) })} className="min-w-0 flex-1 appearance-none rounded-none border border-[var(--dash-border)] bg-[var(--dash-input)] px-2 py-1.5 text-center text-xs text-[var(--dash-text)] outline-none [caret-color:auto] [-moz-appearance:textfield] [&::-webkit-inner-spin-button]:m-0 [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:m-0 [&::-webkit-outer-spin-button]:appearance-none" /><button type="button" data-custom-die-value-decrement aria-label="Diminuisci valore" onClick={() => stepFaceValue(pos, -1)} className="w-8 shrink-0 rounded-r-md border border-l-0 border-[var(--dash-border)] bg-[var(--dash-input)] text-sm font-semibold text-[var(--dash-text)] hover:bg-[var(--dash-surface-2)]">-</button></div>
      {resultDisplayMode === 'grouped' && <label data-custom-die-face-group className="mt-2 flex items-center gap-2 text-[10px] text-[var(--dash-muted)]"><span className="shrink-0">Gruppo</span><input type="number" min={1} step={1} inputMode="numeric" placeholder="Nessuno" value={face.resultGroup ?? ''} onChange={(event) => patchFace(pos, { resultGroup: event.target.value === '' ? null : Number(event.target.value) })} className="min-w-0 flex-1 appearance-none rounded-md border border-[var(--dash-border)] bg-[var(--dash-input)] px-2 py-1.5 text-center text-xs text-[var(--dash-text)] outline-none [caret-color:auto] [-moz-appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none" /></label>}
    </div>; })}</div>}
      <section data-custom-die-appearance-controls className="rounded-xl border border-[var(--dash-border)] bg-[var(--dash-surface)] p-3"><div data-custom-die-skin-controls><div className="mb-1 text-xs text-[var(--dash-muted)]">Skin</div><div className="grid grid-cols-3 gap-1 sm:grid-cols-5 xl:grid-cols-9">{DICE_SKINS.map((skin) => { const preview = { ...appearance, skinId: skin.id }; return <button key={skin.id} type="button" data-custom-die-skin={skin.id} aria-pressed={skinId === skin.id} title={skin.label} onClick={() => setSkinId(skin.id)} className={`overflow-hidden rounded-md border p-1 ${skinId === skin.id ? 'border-[var(--dash-accent)] ring-1 ring-[var(--dash-accent)]/30' : 'border-[var(--dash-border)]'}`}><DiceSkinSurface appearance={preview} illustrative className="block h-6 rounded-sm" /><span className="mt-0.5 block truncate text-[8px] text-[var(--dash-muted)]">{skin.label}</span></button>; })}</div></div><div className="mt-3 grid items-stretch gap-2 sm:grid-cols-[minmax(0,2fr)_minmax(12rem,1fr)]"><label className="block rounded-lg border border-[var(--dash-border)] bg-[var(--dash-panel)] p-2"><span className="flex items-center justify-between gap-2 text-xs text-[var(--dash-muted)]"><span>Zoom texture</span><span data-custom-die-texture-scale-value className="font-semibold tabular-nums text-[var(--dash-text-strong)]">{textureScale}%</span></span><input data-custom-die-texture-scale aria-label="Zoom texture" type="range" min={MIN_DICE_TEXTURE_SCALE} max={MAX_DICE_TEXTURE_SCALE} step={1} value={textureScale} onChange={(event) => setTextureScale(normalizeDiceTextureScale(Number(event.target.value)))} className="mt-2 w-full cursor-pointer" style={{ accentColor: 'var(--dash-accent)' }} /><span className="mt-1 flex justify-between text-[9px] text-[var(--dash-muted)]"><span>{MIN_DICE_TEXTURE_SCALE}%</span><span>{MAX_DICE_TEXTURE_SCALE}%</span></span></label><label className="flex items-center justify-between gap-2 rounded-lg border border-[var(--dash-border)] bg-[var(--dash-panel)] px-3 py-2"><span className="text-xs text-[var(--dash-muted)]">Effetti animati</span><Switch data-custom-die-effects checked={effectsEnabled} onCheckedChange={setEffectsEnabled} /></label></div></section>
    </section></div>
    <footer className="flex justify-end gap-2 border-t border-[var(--dash-border)] p-4"><button onClick={cancel} className="rounded-lg border border-[var(--dash-border)] px-4 py-2 text-sm text-[var(--dash-muted)]">Annulla</button><button disabled={!validation.valid || busy} onClick={async () => { setBusy(true); try { await onSave({ id, name: name.trim(), sides, quickRollQuantity, definitionMode, resultDisplayMode, faces, bodyColor, symbolColor, skinId, effectsEnabled, textureScale }); } finally { setBusy(false); } }} className="inline-flex items-center gap-2 rounded-lg bg-[var(--dash-accent)] px-4 py-2 text-sm font-semibold text-[var(--dash-text-strong)] disabled:opacity-40"><Save className="h-4 w-4" />{busy ? 'Salvataggio…' : 'Salva dado'}</button></footer>
  </div></div>;
}
