import { useState } from 'react';
import { Palette } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipTrigger } from '../../ui/tooltip';
import { DiceTypeIcon } from './DiceTypeIcon';
import { CustomDiceQuestionIcon } from './CustomDiceQuestionIcon';
import { DiceAppearanceCustomizer } from './DiceAppearanceCustomizer';
import { useDiceAppearance } from './DiceAppearanceContext';
import type { DiceFormulaItem, SavedCustomDie } from './diceTypes.ts';
export const QUICK_DICE_SIDES = [4, 6, 8, 10, 12, 20, 100] as const;
export function DiceToolbar({items,onAddDie,onCreateCustomDie}:{items:DiceFormulaItem[];onAddDie:(sides:number)=>void;customDice?:SavedCustomDie[];onAddCustomDie?:(die:SavedCustomDie)=>void;onCreateCustomDie?:()=>void}){const{isLoading:appearanceLoading}=useDiceAppearance();const[appearanceOpen,setAppearanceOpen]=useState(false);return <><div className="relative flex flex-wrap gap-2" data-dice-quick-toolbar>{QUICK_DICE_SIDES.map(sides=>{const quantity=items.filter((item):item is Extract<DiceFormulaItem,{kind:'dice'}>=>item.kind==='dice'&&item.sides===sides).reduce((sum,item)=>sum+item.quantity,0);return <Tooltip key={sides}><TooltipTrigger asChild><button type="button" data-dice-quick-side={sides} onClick={()=>onAddDie(sides)} className="group relative flex h-16 min-w-16 items-center justify-center rounded-lg border border-[var(--dash-border)] bg-[var(--dash-surface)] px-2 text-[var(--dash-text)] transition-colors hover:border-[var(--dash-accent)] hover:bg-[var(--dash-surface-2)]" aria-label={`Aggiungi d${sides}`}>{quantity>0&&<span className="absolute -right-1.5 -top-1.5 flex h-5 min-w-5 items-center justify-center rounded-full bg-[var(--dash-accent)] px-1 text-[10px] font-bold text-[var(--dash-text-strong)] shadow">{quantity}</span>}<DiceTypeIcon sides={sides} className={sides===100?'h-11 w-16 transition-transform group-hover:scale-110':'h-12 w-12 transition-transform group-hover:scale-110'}/></button></TooltipTrigger><TooltipContent>{`d${sides}`}</TooltipContent></Tooltip>})}<Tooltip><TooltipTrigger asChild><button type="button" data-dice-custom-toolbar onClick={()=>onCreateCustomDie?.()} className="group relative flex h-16 min-w-16 items-center justify-center rounded-lg border border-[var(--dash-border)] bg-[var(--dash-surface)] text-[var(--dash-accent)] hover:border-[var(--dash-accent)]"><CustomDiceQuestionIcon className="h-12 w-12 transition-transform group-hover:scale-110"/></button></TooltipTrigger><TooltipContent>Dado Custom</TooltipContent></Tooltip><Tooltip><TooltipTrigger asChild><button type="button" data-dice-appearance-toolbar aria-label="Personalizza" disabled={appearanceLoading} onClick={()=>setAppearanceOpen(true)} className="group relative flex h-16 min-w-16 items-center justify-center rounded-lg border border-[var(--dash-border)] bg-[var(--dash-surface)] text-[var(--dash-accent)] hover:border-[var(--dash-accent)] disabled:cursor-wait disabled:opacity-50"><Palette className="h-9 w-9 transition-transform group-hover:scale-110"/></button></TooltipTrigger><TooltipContent>Personalizza</TooltipContent></Tooltip></div>{appearanceOpen&&<DiceAppearanceCustomizer onClose={()=>setAppearanceOpen(false)}/>}</>}
